const defaultConfig = {
  leagueName: 'Premier Player League',
  leagueSeason: 'Season 7',
  leagueLogo: '',
  minPlayersPerTeam: 10,
  thresholdBid: 200,
  highIncrement: 20,
  lowIncrement: 10,
  auctionTimerSeconds: 30,
  teamBudgetLimit: 1500,
  adminPassword: 'ppl2024',
};

const defaultPlayers = [
  { id: 1, name: 'Arjun Menon', position: 'GK', rating: 82, basePrice: 100, photo: '', status: 'available' },
  { id: 2, name: 'Rahul Das', position: 'CB', rating: 78, basePrice: 100, photo: '', status: 'available' },
  { id: 3, name: 'Vishnu Kumar', position: 'CB', rating: 80, basePrice: 100, photo: '', status: 'available' },
  { id: 4, name: 'Amal Raj', position: 'LB', rating: 75, basePrice: 100, photo: '', status: 'available' },
  { id: 5, name: 'Siddharth Nair', position: 'RB', rating: 76, basePrice: 100, photo: '', status: 'available' },
  { id: 6, name: 'Mohammed Shan', position: 'CM', rating: 85, basePrice: 100, photo: '', status: 'available' },
  { id: 7, name: 'Kevin Jose', position: 'CM', rating: 83, basePrice: 100, photo: '', status: 'available' },
  { id: 8, name: 'Adil Hussain', position: 'CAM', rating: 87, basePrice: 100, photo: '', status: 'available' },
  { id: 9, name: 'Rohan Pillai', position: 'LW', rating: 84, basePrice: 100, photo: '', status: 'available' },
  { id: 10, name: 'Arshad Ali', position: 'RW', rating: 86, basePrice: 100, photo: '', status: 'available' },
  { id: 11, name: 'Sajith Thomas', position: 'ST', rating: 90, basePrice: 150, photo: '', status: 'available' },
  { id: 12, name: 'Nikhil Varma', position: 'ST', rating: 88, basePrice: 150, photo: '', status: 'available' },
  { id: 13, name: 'Faisal Moosa', position: 'GK', rating: 79, basePrice: 100, photo: '', status: 'available' },
  { id: 14, name: 'Anand Srikumar', position: 'LW', rating: 81, basePrice: 100, photo: '', status: 'available' },
  { id: 15, name: 'Deepak Suresh', position: 'CDM', rating: 77, basePrice: 100, photo: '', status: 'available' },
  { id: 16, name: 'Jithin George', position: 'RW', rating: 83, basePrice: 100, photo: '', status: 'available' },
  { id: 17, name: 'Vineeth Mohan', position: 'CB', rating: 74, basePrice: 100, photo: '', status: 'available' },
  { id: 18, name: 'Sarath Nair', position: 'CM', rating: 82, basePrice: 100, photo: '', status: 'available' },
  { id: 19, name: 'Bibin Chacko', position: 'LB', rating: 76, basePrice: 100, photo: '', status: 'available' },
  { id: 20, name: 'Aswin Raj', position: 'ST', rating: 85, basePrice: 120, photo: '', status: 'available' },
  { id: 21, name: 'Midhun PS', position: 'CDM', rating: 78, basePrice: 100, photo: '', status: 'available' },
  { id: 22, name: 'Shafeeq Ali', position: 'CAM', rating: 84, basePrice: 100, photo: '', status: 'available' },
  { id: 23, name: 'Rohit Varma', position: 'GK', rating: 81, basePrice: 100, photo: '', status: 'available' },
  { id: 24, name: 'Nirmal Dev', position: 'RB', rating: 77, basePrice: 100, photo: '', status: 'available' },
  { id: 25, name: 'Fazil Hameed', position: 'ST', rating: 88, basePrice: 140, photo: '', status: 'available' },
  { id: 26, name: 'Dipin George', position: 'LW', rating: 80, basePrice: 100, photo: '', status: 'available' },
  { id: 27, name: 'Athul Suresh', position: 'RW', rating: 82, basePrice: 100, photo: '', status: 'available' },
  { id: 28, name: 'Jibin Mathew', position: 'CM', rating: 79, basePrice: 100, photo: '', status: 'available' },
  { id: 29, name: 'Anas Farooq', position: 'CB', rating: 76, basePrice: 100, photo: '', status: 'available' },
  { id: 30, name: 'Sreejith KP', position: 'ST', rating: 86, basePrice: 130, photo: '', status: 'available' },
  { id: 31, name: 'Alan Abraham', position: 'CAM', rating: 83, basePrice: 100, photo: '', status: 'available' },
  { id: 32, name: 'Rahul Mathews', position: 'CDM', rating: 80, basePrice: 100, photo: '', status: 'available' },
  { id: 33, name: 'Unni Krishnan', position: 'LB', rating: 75, basePrice: 100, photo: '', status: 'available' },
  { id: 34, name: 'Pradeep CK', position: 'CB', rating: 77, basePrice: 100, photo: '', status: 'available' },
  { id: 35, name: 'Sooraj Thomas', position: 'RB', rating: 76, basePrice: 100, photo: '', status: 'available' },
  { id: 36, name: 'Muhammed Rafi', position: 'CM', rating: 81, basePrice: 100, photo: '', status: 'available' },
  { id: 37, name: 'Akash Mohan', position: 'LW', rating: 79, basePrice: 100, photo: '', status: 'available' },
  { id: 38, name: 'Vishnu Prasad', position: 'GK', rating: 78, basePrice: 100, photo: '', status: 'available' },
  { id: 39, name: 'Arif Shameer', position: 'ST', rating: 84, basePrice: 110, photo: '', status: 'available' },
  { id: 40, name: 'Joel James', position: 'RW', rating: 80, basePrice: 100, photo: '', status: 'available' },
];

const defaultTeams = [
  { id: 'T1', name: 'Thunder FC', color: '#e63946', logo: '', budget: 1500, spent: 0, players: [] },
  { id: 'T2', name: 'Strikers SC', color: '#4895ef', logo: '', budget: 1500, spent: 0, players: [] },
  { id: 'T3', name: 'Royal Eagles', color: '#f4a261', logo: '', budget: 1500, spent: 0, players: [] },
  { id: 'T4', name: 'Green Wolves', color: '#2dc653', logo: '', budget: 1500, spent: 0, players: [] },
];

const defaultAuctionState = {
  phase: 'idle',
  currentPlayer: null,
  currentBid: 0,
  leadingTeam: null,
  bidHistory: [],
  soldPlayers: [],
  timerSeconds: 10,
  timerEndsAt: null,
};

module.exports = {
  defaultConfig,
  defaultPlayers,
  defaultTeams,
  defaultAuctionState,
};
